kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}
